{{- if .Values.backend.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vectaris.fullname" . }}-backend-secrets
  labels:
    {{- include "vectaris.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.backend.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
